import axios from 'axios';
import {
  User,
  Complaint,
  Poll,
  Notification,
  AuditLog,
  Department,
  UserRole,
} from '../types';

const API_BASE_URL = import.meta.env.VITE_API_URL || '/api';

export const apiClient = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
  timeout: 10000,
});

apiClient.interceptors.request.use((config) => {
  const token = localStorage.getItem('token');
  if (token && config.headers) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// Initial In-Memory Mock Store for offline resilience
export const MOCK_USERS: User[] = [
  {
    id: 'u-1',
    name: 'Aarav Sharma',
    email: 'aarav.student@campuspulse.edu',
    role: 'student',
    hostelBlock: 'Block B',
    roomNumber: '304',
    phone: '+91 98765 43210',
    createdAt: '2026-01-15T08:00:00.000Z',
  },
  {
    id: 'u-2',
    name: 'Prof. Rajesh Verma',
    email: 'rajesh.it@campuspulse.edu',
    role: 'dept_admin',
    departmentId: 'dept-it',
    departmentName: 'IT Infrastructure & Wi-Fi',
    phone: '+91 98765 43211',
    createdAt: '2025-08-10T08:00:00.000Z',
  },
  {
    id: 'u-3',
    name: 'Dr. Sunita Rao',
    email: 'sunita.dean@campuspulse.edu',
    role: 'management',
    departmentName: 'Dean of Student Affairs',
    phone: '+91 98765 43212',
    createdAt: '2025-06-01T08:00:00.000Z',
  },
  {
    id: 'u-4',
    name: 'Super Administrator',
    email: 'admin@campuspulse.edu',
    role: 'superadmin',
    phone: '+91 98765 43213',
    createdAt: '2025-01-01T08:00:00.000Z',
  },
];

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: 'c-101',
    trackingCode: 'CP-2026-101',
    title: 'Wi-Fi completely offline in Hostel Block B, Floor 2 & 3',
    description:
      'The access point AP-B201 in the corridor has been flashing red since 9:00 PM yesterday. Students are unable to access LMS or submit lab records.',
    category: 'IT Infrastructure & Wi-Fi',
    urgency: 'high',
    urgencyScore: 0.82,
    status: 'in_progress',
    location: 'Hostel Block B, 2nd & 3rd Floor',
    studentId: 'u-1',
    studentName: 'Aarav Sharma',
    departmentId: 'dept-it',
    departmentName: 'IT Infrastructure & Wi-Fi',
    sentiment: 'negative',
    sentimentScore: -0.65,
    upvotes: 42,
    upvotedBy: ['u-1', 'u-5', 'u-6'],
    tags: ['wifi', 'network', 'hostel-b'],
    aiSummary:
      'Router access point AP-B201 flashing red since last night affecting second and third-floor hostel residents preparing for project submissions.',
    aiClassificationConfidence: 0.96,
    subTickets: [
      {
        id: 'st-1',
        complaintId: 'c-101',
        title: 'Dispatch network engineer with spare Cisco AP',
        status: 'in_progress',
        priority: 'high',
        assignedToName: 'Manoj Kumar (IT Tech)',
        createdAt: '2026-09-08T10:00:00.000Z',
      },
    ],
    comments: [
      {
        id: 'cm-1',
        authorId: 'u-2',
        authorName: 'Prof. Rajesh Verma',
        authorRole: 'dept_admin',
        text: 'Technician has been dispatched with a replacement AP unit. Expected resolution by 2:00 PM.',
        createdAt: '2026-09-08T10:30:00.000Z',
      },
    ],
    createdAt: '2026-09-08T09:15:00.000Z',
  },
  {
    id: 'c-102',
    trackingCode: 'CP-2026-102',
    title: 'Severe water leakage near electrical switchboard in Room 412',
    description:
      'Water is dripping directly from the ceiling pipe onto the main socket switchboard. There is a potential risk of electric shock.',
    category: 'Hostel & Residential Life',
    urgency: 'critical',
    urgencyScore: 0.98,
    status: 'escalated',
    location: 'Hostel Block A, Room 412',
    studentId: 'u-10',
    studentName: 'Priya Patel',
    departmentId: 'dept-hostel',
    departmentName: 'Hostel & Residential Life',
    sentiment: 'negative',
    sentimentScore: -0.88,
    upvotes: 68,
    upvotedBy: ['u-10', 'u-1', 'u-7'],
    tags: ['electrical-hazard', 'plumbing', 'emergency'],
    aiSummary:
      'Critical life-safety hazard: water leaking directly onto active electrical sockets in Room 412.',
    aiClassificationConfidence: 0.99,
    subTickets: [
      {
        id: 'st-2',
        complaintId: 'c-102',
        title: 'Cut power breaker to Wing 4 immediately',
        status: 'completed',
        priority: 'critical',
        assignedToName: 'Ramesh Electrical',
        createdAt: '2026-09-09T06:15:00.000Z',
      },
      {
        id: 'st-3',
        complaintId: 'c-102',
        title: 'Plumber inspection for ceiling joint pipe crack',
        status: 'in_progress',
        priority: 'critical',
        assignedToName: 'Suresh Plumbing',
        createdAt: '2026-09-09T06:30:00.000Z',
      },
    ],
    createdAt: '2026-09-09T06:00:00.000Z',
  },
  {
    id: 'c-103',
    trackingCode: 'CP-2026-103',
    title: 'Cafeteria hygiene: Unwashed trays and cold breakfast served',
    description:
      'The morning breakfast trays had grease stains and tea was served lukewarm. Several students raised complaints with mess supervisors.',
    category: 'Cafeteria & Food Services',
    urgency: 'medium',
    urgencyScore: 0.58,
    status: 'submitted',
    location: 'Central Dining Hall',
    studentId: 'u-11',
    studentName: 'Karan Mehra',
    departmentId: 'dept-canteen',
    departmentName: 'Cafeteria & Food Services',
    sentiment: 'negative',
    sentimentScore: -0.45,
    upvotes: 31,
    upvotedBy: ['u-11'],
    tags: ['food-quality', 'hygiene', 'canteen'],
    aiSummary:
      'Hygiene issues with utensils and food temperature reported at the Central Dining Hall during breakfast service.',
    aiClassificationConfidence: 0.92,
    createdAt: '2026-09-09T07:30:00.000Z',
  },
  {
    id: 'c-104',
    trackingCode: 'CP-2026-104',
    title: 'Projector in Mechanical Seminar Hall 2 display distorted',
    description:
      'The HDMI signal loses sync every 3 minutes. The screen flickers with green vertical lines during seminar presentations.',
    category: 'Classroom & Academic Labs',
    urgency: 'medium',
    urgencyScore: 0.52,
    status: 'triaged',
    location: 'Mech Block, Seminar Hall 2',
    studentId: 'u-1',
    studentName: 'Aarav Sharma',
    departmentId: 'dept-acad',
    departmentName: 'Classroom & Academic Labs',
    sentiment: 'neutral',
    sentimentScore: -0.15,
    upvotes: 12,
    upvotedBy: ['u-1'],
    tags: ['projector', 'av-equipment'],
    aiSummary: 'AV display signal flickers periodically due to faulty HDMI input cabling.',
    aiClassificationConfidence: 0.88,
    createdAt: '2026-09-07T14:20:00.000Z',
  },
  {
    id: 'c-105',
    trackingCode: 'CP-2026-105',
    title: 'Library 3rd floor reading room AC making grinding noise',
    description:
      'The split AC in the quiet zone has a defective blower fan causing loud vibrations.',
    category: 'Library Services',
    urgency: 'low',
    urgencyScore: 0.32,
    status: 'resolved',
    location: 'Central Library, 3rd Floor',
    studentId: 'u-14',
    studentName: 'Sneha Gupta',
    departmentId: 'dept-library',
    departmentName: 'Library Services',
    sentiment: 'positive',
    sentimentScore: 0.65,
    upvotes: 19,
    resolvedAt: '2026-09-08T16:00:00.000Z',
    createdAt: '2026-09-06T11:00:00.000Z',
  },
];

export const MOCK_POLLS: Poll[] = [
  {
    id: 'poll-1',
    title: 'Extension of Central Library Operating Hours',
    description:
      'Management is evaluating extending library reading room timings till 2:00 AM during mid-term and end-term exams.',
    category: 'Library Services',
    options: [
      { id: 'opt-1', text: 'Strongly Agree (Keep open until 2:00 AM)', votes: 248 },
      { id: 'opt-2', text: 'Keep 24/7 during final exam weeks only', votes: 192 },
      { id: 'opt-3', text: 'Current timings (11:00 PM) are adequate', votes: 34 },
    ],
    status: 'active',
    totalVotes: 474,
    expiresAt: '2026-09-20T23:59:59.000Z',
    createdBy: 'u-3',
    createdByName: 'Dr. Sunita Rao (Dean)',
    hasVoted: false,
    createdAt: '2026-09-01T09:00:00.000Z',
  },
  {
    id: 'poll-2',
    title: 'Weekend Breakfast Menu Overhaul in Dining Halls',
    description:
      'Gathering student opinions on introducing South Indian & Continental combo options on Saturday and Sunday mornings.',
    category: 'Cafeteria & Food Services',
    options: [
      { id: 'opt-201', text: 'Introduce Masala Dosa & Idli platter', votes: 312 },
      { id: 'opt-202', text: 'Pancake & Waffle bar option', votes: 184 },
      { id: 'opt-203', text: 'Retain current Poha & Paratha rotation', votes: 67 },
    ],
    status: 'active',
    totalVotes: 563,
    expiresAt: '2026-09-18T23:59:59.000Z',
    createdBy: 'u-3',
    createdByName: 'Student Welfare Committee',
    hasVoted: true,
    userVotedOptionId: 'opt-201',
    createdAt: '2026-09-02T10:00:00.000Z',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n-1',
    userId: 'u-1',
    type: 'status_updated',
    title: 'Complaint In Progress',
    message: 'Technician Manoj Kumar was assigned to your Wi-Fi issue (CP-2026-101).',
    read: false,
    complaintId: 'c-101',
    createdAt: '2026-09-08T10:05:00.000Z',
  },
  {
    id: 'n-2',
    userId: 'u-1',
    type: 'poll_published',
    title: 'New Campus Poll Active',
    message: 'Dean Rao published: "Extension of Central Library Operating Hours". Cast your vote!',
    read: false,
    createdAt: '2026-09-01T09:15:00.000Z',
  },
  {
    id: 'n-3',
    userId: 'u-1',
    type: 'upvote_milestone',
    title: 'Community Milestone',
    message: 'Your complaint regarding Block B Wi-Fi has reached 40+ student upvotes.',
    read: true,
    complaintId: 'c-101',
    createdAt: '2026-09-08T14:30:00.000Z',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    userId: 'u-2',
    userName: 'Prof. Rajesh Verma',
    userRole: 'dept_admin',
    action: 'STATUS_UPDATE',
    resource: 'Complaint',
    resourceId: 'c-101',
    details: 'Status transitioned from TRIAGED to IN_PROGRESS. Assigned sub-ticket to Manoj Kumar.',
    ipAddress: '10.0.4.12',
    timestamp: '2026-09-08T10:00:00.000Z',
  },
  {
    id: 'aud-2',
    userId: 'u-4',
    userName: 'Super Administrator',
    userRole: 'superadmin',
    action: 'USER_ROLE_CHANGE',
    resource: 'User',
    resourceId: 'u-2',
    details: 'Updated role permissions for Rajesh Verma to Dept Admin (IT Infrastructure).',
    ipAddress: '10.0.0.1',
    timestamp: '2026-09-05T14:22:00.000Z',
  },
  {
    id: 'aud-3',
    userId: 'u-3',
    userName: 'Dr. Sunita Rao',
    userRole: 'management',
    action: 'POLL_PUBLISH',
    resource: 'Poll',
    resourceId: 'poll-1',
    details: 'Published campus-wide survey: Extension of Central Library Operating Hours.',
    ipAddress: '10.0.2.88',
    timestamp: '2026-09-01T09:00:00.000Z',
  },
  {
    id: 'aud-4',
    userId: 'u-2',
    userName: 'Prof. Rajesh Verma',
    userRole: 'dept_admin',
    action: 'SUB_TICKET_CREATE',
    resource: 'SubTicket',
    resourceId: 'st-1',
    details: 'Generated sub-ticket: Dispatch network engineer with spare Cisco AP.',
    ipAddress: '10.0.4.12',
    timestamp: '2026-09-08T10:01:00.000Z',
  },
];

export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: 'dept-it',
    name: 'IT Infrastructure & Wi-Fi',
    code: 'ITW',
    headName: 'Prof. Rajesh Verma',
    headEmail: 'rajesh.it@campuspulse.edu',
    activeTicketsCount: 14,
    slaResolutionRate: 94.2,
  },
  {
    id: 'dept-hostel',
    name: 'Hostel & Residential Life',
    code: 'HRL',
    headName: 'Chief Warden Saxena',
    headEmail: 'warden@campuspulse.edu',
    activeTicketsCount: 22,
    slaResolutionRate: 88.5,
  },
  {
    id: 'dept-canteen',
    name: 'Cafeteria & Food Services',
    code: 'CFS',
    headName: 'Anil Kapoor',
    headEmail: 'cafeteria@campuspulse.edu',
    activeTicketsCount: 9,
    slaResolutionRate: 91.0,
  },
  {
    id: 'dept-acad',
    name: 'Classroom & Academic Labs',
    code: 'CAL',
    headName: 'Dr. Meenakshi',
    headEmail: 'academic.facilities@campuspulse.edu',
    activeTicketsCount: 7,
    slaResolutionRate: 96.5,
  },
  {
    id: 'dept-security',
    name: 'Campus Security & Safety',
    code: 'CSS',
    headName: 'Capt. R. S. Rana',
    headEmail: 'security@campuspulse.edu',
    activeTicketsCount: 3,
    slaResolutionRate: 99.0,
  },
];
