from pydantic import BaseModel, Field
from typing import Optional

class SummarizeRequest(BaseModel):
    text: str = Field(..., min_length=10, description="Complaint text or combined tickets to summarize")
    max_length: Optional[int] = Field(130, ge=20, le=512, description="Maximum length of the generated summary")
    min_length: Optional[int] = Field(30, ge=10, le=256, description="Minimum length of the generated summary")

class SummarizeResponse(BaseModel):
    summary: str = Field(..., description="Executive summary generated by facebook/bart-large-cnn")
    original_characters: int
    summary_characters: int
    compression_ratio: float = Field(..., description="Ratio of summary length to original length")
